# Generated by Django 4.0.3 on 2022-05-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bqt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datebqt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Declenchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Priorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Statusbqt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Statusrapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Toc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numerotoc', models.CharField(max_length=50)),
                ('priorite', models.CharField(default='', max_length=4)),
                ('pays', models.CharField(default='', max_length=15)),
                ('Datedebut', models.DateTimeField()),
                ('Datefin', models.DateTimeField()),
                ('Rapport', models.CharField(default='', max_length=500)),
                ('Description', models.CharField(default='', max_length=500)),
                ('SerPlat', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Typrobleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(default='', max_length=300)),
                ('Prenom', models.CharField(default='', max_length=300)),
                ('Poste', models.CharField(default='', max_length=100)),
                ('Rang', models.CharField(default='', max_length=100)),
                ('Email', models.EmailField(max_length=50)),
                ('Contact', models.IntegerField()),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='rai.role')),
            ],
        ),
        migrations.CreateModel(
            name='UserConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rai.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tocprobleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numerotocpro', models.CharField(max_length=50)),
                ('typeproblem', models.CharField(default='', max_length=30)),
                ('Porteur', models.CharField(default='', max_length=100)),
                ('Date', models.DateField()),
                ('Dtatustocprob', models.CharField(default='', max_length=500)),
                ('Priorite', models.CharField(default='', max_length=500)),
                ('toc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tocpro', to='rai.toc')),
            ],
        ),
        migrations.CreateModel(
            name='Rai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=10)),
                ('critere', models.CharField(default='', max_length=10)),
                ('declenchement', models.IntegerField()),
                ('Rapportredige', models.CharField(default='', max_length=5)),
                ('Rapportpartage', models.CharField(default='', max_length=5)),
                ('Comptrendus', models.CharField(default='', max_length=5)),
                ('Cause', models.CharField(default='', max_length=200)),
                ('Rootcause', models.CharField(default='', max_length=200)),
                ('Statrootcause', models.CharField(default='', max_length=200)),
                ('Actionretablissement', models.CharField(default='', max_length=200)),
                ('Datecritere', models.DateField()),
                ('Typesolution', models.CharField(default='', max_length=100)),
                ('Commentaire', models.CharField(default='', max_length=100)),
                ('DateRept', models.DateField()),
                ('Rirecu', models.CharField(default='', max_length=5)),
                ('JoinToc', models.CharField(default='', max_length=5)),
                ('tocprobleme', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rai', to='rai.tocprobleme')),
            ],
        ),
        migrations.CreateModel(
            name='Planactionbqt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
                ('Porteur', models.CharField(default='', max_length=300)),
                ('Dateprevisionel', models.DateField()),
                ('Dateeffective', models.DateField()),
                ('Status', models.CharField(default='', max_length=50)),
                ('Commentaire', models.CharField(default='', max_length=500)),
                ('bqt', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='planbqt', to='rai.bqt')),
            ],
        ),
        migrations.CreateModel(
            name='Planaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
                ('Porteur', models.CharField(default='', max_length=300)),
                ('Dateprevisionel', models.DateField()),
                ('Dateeffective', models.DateField()),
                ('Status', models.CharField(default='', max_length=50)),
                ('Commentaire', models.CharField(default='', max_length=500)),
                ('tocprobleme', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='planrai', to='rai.tocprobleme')),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
                ('mois', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='periode', to='rai.mois')),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=500)),
                ('Platform', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Impact', to='rai.platform')),
                ('service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Impact', to='rai.service')),
                ('toc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Impact', to='rai.toc')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluationbqt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Efficacite', models.CharField(default='', max_length=70)),
                ('Commentaire', models.CharField(default='', max_length=500)),
                ('planactionbqt', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evalbqt', to='rai.planactionbqt')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Efficacite', models.CharField(default='', max_length=70)),
                ('Commentaire', models.CharField(default='', max_length=500)),
                ('Planaction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='evalrai', to='rai.planaction')),
            ],
        ),
        migrations.AddField(
            model_name='bqt',
            name='periode',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bqt', to='rai.periode'),
        ),
        migrations.AddField(
            model_name='bqt',
            name='platform',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bqt', to='rai.platform'),
        ),
        migrations.AddField(
            model_name='bqt',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bqt', to='rai.service'),
        ),
        migrations.AddField(
            model_name='bqt',
            name='statusbqt',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bqt', to='rai.statusbqt'),
        ),
    ]
