# Generated by Django 4.0.3 on 2022-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toc',
            name='Timeglobal',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='toc',
            name='Datedebut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='toc',
            name='Datefin',
            field=models.DateField(),
        ),
    ]
