# Generated by Django 4.0.3 on 2022-05-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0002_toc_timeglobal_alter_toc_datedebut_alter_toc_datefin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toc',
            name='Timeglobal',
        ),
    ]
