# Generated by Django 4.0.3 on 2022-05-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0003_remove_toc_timeglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaction',
            name='NatureIncident',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='planaction',
            name='Perimetre',
            field=models.CharField(default='', max_length=500),
        ),
    ]
