# Generated by Django 4.0.3 on 2022-05-12 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0005_remove_evaluation_planaction_delete_planaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NatureIncident', models.CharField(default='', max_length=200)),
                ('tocprobleme', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='rai.tocprobleme')),
            ],
        ),
        migrations.CreateModel(
            name='Planactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle', models.CharField(default='', max_length=200)),
                ('Porteur', models.CharField(default='', max_length=300)),
                ('Dateprevisionel', models.DateField()),
                ('Dateeffective', models.DateField()),
                ('Dateevaluation', models.DateField()),
                ('Perimetre', models.CharField(default='', max_length=500)),
                ('Status', models.IntegerField()),
                ('Efficacite', models.CharField(default='', max_length=50)),
                ('Commentaire', models.CharField(default='', max_length=500)),
                ('incident', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='planrai', to='rai.incident')),
            ],
        ),
    ]
