# Generated by Django 4.0.3 on 2022-05-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0006_incident_planactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planactions',
            name='Dateevaluation',
        ),
    ]
