# Generated by Django 4.0.3 on 2022-05-16 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0008_tocticket_remove_planactions_incident_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planactions',
            old_name='Tocprobleme',
            new_name='tocprobleme',
        ),
    ]
