# Generated by Django 4.0.3 on 2022-05-16 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0009_rename_tocprobleme_planactions_tocprobleme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tocprobleme',
            name='Numerotocpro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tocticket',
            name='toc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tocticket', to='rai.toc'),
        ),
    ]
