# Generated by Django 4.0.3 on 2022-05-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0011_alter_tocprobleme_numerotocpro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planactions',
            name='tocprobleme',
        ),
    ]
