# Generated by Django 4.0.3 on 2022-05-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0012_remove_planactions_tocprobleme'),
    ]

    operations = [
        migrations.AddField(
            model_name='planactions',
            name='tocpr',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.CASCADE, related_name='planrai', to='rai.tocprobleme'),
            preserve_default=False,
        ),
    ]
