# Generated by Django 4.0.3 on 2022-05-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0013_planactions_tocpr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocticket',
            name='toc',
        ),
        migrations.AddField(
            model_name='toc',
            name='toctik',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toc', to='rai.tocticket'),
            preserve_default=False,
        ),
    ]
