# Generated by Django 4.0.3 on 2022-05-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0014_remove_tocticket_toc_toc_toctik'),
    ]

    operations = [
        migrations.AddField(
            model_name='toc',
            name='heurD',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toc',
            name='heurF',
            field=models.TimeField(default='00:00'),
            preserve_default=False,
        ),
    ]
