# Generated by Django 4.0.3 on 2022-05-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0015_toc_heurd_toc_heurf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toc',
            name='Datedebut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='toc',
            name='Datefin',
            field=models.DateTimeField(),
        ),
    ]
