# Generated by Django 4.0.3 on 2022-05-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0017_alter_toc_datedebut_alter_toc_datefin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toc',
            name='Datedebut',
            field=models.DateField(default='16.05.2022 22:10:58'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='Datefin',
            field=models.DateField(default='16.05.2022 22:10:58'),
        ),
    ]
