# Generated by Django 4.0.3 on 2022-05-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0018_alter_toc_datedebut_alter_toc_datefin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toc',
            name='Datedebut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='toc',
            name='Datefin',
            field=models.DateField(),
        ),
    ]
