# Generated by Django 4.0.3 on 2022-05-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0019_alter_toc_datedebut_alter_toc_datefin'),
    ]

    operations = [
        migrations.AddField(
            model_name='toc',
            name='SerPlat',
            field=models.CharField(default='', max_length=20),
        ),
    ]
