# Generated by Django 4.0.3 on 2022-05-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0020_toc_serplat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocprobleme',
            name='Dtatustocprob',
        ),
    ]
