# Generated by Django 4.0.3 on 2022-05-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0021_remove_tocprobleme_dtatustocprob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocprobleme',
            name='Date',
        ),
    ]
