# Generated by Django 4.0.5 on 2022-06-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0022_remove_tocprobleme_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='planactionbqt',
            name='Efficacite',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='planactionbqt',
            name='Perimetre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='planactionbqt',
            name='Status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
