# Generated by Django 4.0.4 on 2022-07-18 02:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0024_remove_bqt_periode_remove_bqt_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toc',
            name='SerPlat',
        ),
        migrations.RemoveField(
            model_name='toc',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='toc',
            name='toctik',
        ),
        migrations.AddField(
            model_name='bqt',
            name='dateTimeOfUploadCompteR',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bqt',
            name='dateTimeOfUploadPowrd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bqt',
            name='uploadedFileCompteR',
            field=models.FileField(null=True, upload_to='Uploaded Files/', verbose_name='bqt doc'),
        ),
        migrations.AddField(
            model_name='bqt',
            name='uploadedFilePword',
            field=models.FileField(null=True, upload_to='Uploaded Files/', verbose_name='bqt doc'),
        ),
        migrations.AddField(
            model_name='pays',
            name='tocpays',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='rai.toc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='tocplat',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plat', to='rai.toc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rai',
            name='EvaluationDate',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='rai',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rai',
            name='uploadedFileRAI',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
        migrations.AddField(
            model_name='rai',
            name='uploadedFileRI',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
        migrations.AddField(
            model_name='service',
            name='tocserv',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='rai.toc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tocticket',
            name='toctiket',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toc', to='rai.toc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Pictur',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='Statut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rai',
            name='Rootcause',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rai',
            name='Statrootcause',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
