# Generated by Django 4.0.3 on 2022-07-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0024_remove_bqt_periode_remove_bqt_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bqt',
            name='dateTimeOfUploadCompteR',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bqt',
            name='dateTimeOfUploadPowrd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bqt',
            name='uploadedFileCompteR',
            field=models.FileField(default=1, upload_to='Uploaded Files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bqt',
            name='uploadedFilePword',
            field=models.FileField(default=1, upload_to='Uploaded Files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rai',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rai',
            name='uploadedFile',
            field=models.FileField(default=1, upload_to='Uploaded Files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Pictur',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
