# Generated by Django 4.0.3 on 2022-07-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0025_bqt_datetimeofuploadcompter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Pictur',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
