# Generated by Django 4.0.3 on 2022-07-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0026_alter_user_pictur'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Statut',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bqt',
            name='uploadedFileCompteR',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
        migrations.AlterField(
            model_name='bqt',
            name='uploadedFilePword',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
        migrations.AlterField(
            model_name='rai',
            name='uploadedFile',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
    ]
