# Generated by Django 4.0.3 on 2022-07-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0028_alter_bqt_uploadedfilecompter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bqt',
            name='uploadedFileCompteR',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
        migrations.AlterField(
            model_name='bqt',
            name='uploadedFilePword',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Statut',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
