# Generated by Django 4.0.3 on 2022-07-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0031_remove_bqt_uploadedfilecompter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rai',
            name='uploadedFile',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
    ]
