# Generated by Django 4.0.3 on 2022-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0032_rai_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rai',
            name='uploadedFileRI',
            field=models.FileField(null=True, upload_to='Uploaded Files/'),
        ),
    ]
