# Generated by Django 4.0.3 on 2022-07-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0035_bqt_uploadedfilecompter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bqt',
            name='uploadedFilePword',
            field=models.FileField(null=True, upload_to='Uploaded Files/', verbose_name='bqt doc'),
        ),
    ]
