# Generated by Django 4.0.3 on 2022-07-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0036_bqt_uploadedfilepword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toc',
            name='SerPlat',
        ),
    ]
