# Generated by Django 4.0.3 on 2022-07-13 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0037_remove_toc_serplat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rai',
            name='EvaluationDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
