# Generated by Django 4.0.3 on 2022-07-13 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0038_rai_evaluationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rai',
            name='EvaluationDate',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='rai',
            name='Rootcause',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rai',
            name='Statrootcause',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
