# Generated by Django 4.0.4 on 2022-07-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0038_remove_impact_platform_remove_impact_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rai',
            name='EvaluationDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
