# Generated by Django 4.0.3 on 2022-07-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0039_alter_rai_evaluationdate_alter_rai_rootcause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impact',
            name='Libelle',
        ),
        migrations.AddField(
            model_name='impact',
            name='pays',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Impact', to='rai.pays'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rai',
            name='Commentaire',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
