# Generated by Django 4.0.3 on 2022-07-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0040_remove_impact_libelle_impact_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bqt',
            name='ComptRendus',
            field=models.CharField(default='', max_length=10),
        ),
    ]
