# Generated by Django 4.0.4 on 2022-07-27 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0041_alter_rai_evaluationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rai',
            name='EvaluationDate',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
