# Generated by Django 4.0.3 on 2022-07-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0042_remove_pays_tocpays_remove_platform_tocplat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impact',
            name='toc',
        ),
    ]
