# Generated by Django 4.0.3 on 2022-07-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0043_remove_impact_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='tocpays',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pays', to='rai.toc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='platform',
            name='tocplat',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plat', to='rai.toc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='tocserv',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='rai.toc'),
            preserve_default=False,
        ),
    ]
