# Generated by Django 4.0.3 on 2022-07-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0044_pays_tocpays_platform_tocplat_service_tocserv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pays',
            name='tocpays',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='tocplat',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tocserv',
        ),
        migrations.AddField(
            model_name='impact',
            name='toc',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Impact', to='rai.toc'),
            preserve_default=False,
        ),
    ]
