# Generated by Django 4.0.3 on 2022-07-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0045_alter_rai_evaluationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rai',
            name='EvaluationDate',
            field=models.DateField(null=True),
        ),
    ]
