# Generated by Django 4.0.3 on 2022-07-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0045_remove_pays_tocpays_remove_platform_tocplat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='Platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Impact', to='rai.platform'),
        ),
        migrations.AlterField(
            model_name='impact',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Impact', to='rai.pays'),
        ),
        migrations.AlterField(
            model_name='impact',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Impact', to='rai.service'),
        ),
    ]
