# Generated by Django 4.0.3 on 2022-07-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0046_alter_impact_platform_alter_impact_pays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impact',
            name='Platform',
        ),
        migrations.RemoveField(
            model_name='impact',
            name='service',
        ),
    ]
