# Generated by Django 4.0.3 on 2022-07-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0047_remove_impact_platform_remove_impact_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impactservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Impacts', to='rai.service')),
                ('toc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Impacts', to='rai.toc')),
            ],
        ),
    ]
